2020-05-12 18:40:57 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "SELECT * FROM NOTA NOTA NOTA[*]"
Syntax error in SQL statement "SELECT * FROM NOTA NOTA NOTA[*]"; SQL statement:
SELECT * FROM NOTA NOTA NOTA [42000-200]
2020-05-12 18:40:59 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "SELECT * FROM NOTA NOTA NOTA[*]"
Syntax error in SQL statement "SELECT * FROM NOTA NOTA NOTA[*]"; SQL statement:
SELECT * FROM NOTA NOTA NOTA [42000-200]
2020-05-13 17:40:01 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "SELECT * FROM USER USER USER_ROLES[*]"
Syntax error in SQL statement "SELECT * FROM USER USER USER_ROLES[*]"; SQL statement:
SELECT * FROM USER USER USER_ROLES [42000-200]
2020-05-13 17:42:54 jdbc[13]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Error de Sintaxis en sentencia SQL "USER[*]"; se esperaba "UPDATE, USE"
Syntax error in SQL statement "USER[*]"; expected "UPDATE, USE"; SQL statement:
USER [42001-200]
2020-05-13 19:22:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Valor demasiado largo para la columna "USUARIO VARBINARY(255)": "X'aced000573720025636f6d2e73616c657369616e6f732e64616d2e44616d4b6565702e6d6f64656c2e557365729b212634ebb154ae0200095a001563726564... (1029)"
Value too long for column "USUARIO VARBINARY(255)": "X'aced000573720025636f6d2e73616c657369616e6f732e64616d2e44616d4b6565702e6d6f64656c2e557365729b212634ebb154ae0200095a001563726564... (1029)"; SQL statement:
insert into nota (contenido, fecha_creacion, fecha_modi, titulo, usuario, id) values (?, ?, ?, ?, ?, ?) [22001-200]
2020-05-13 19:26:41 jdbc[3]: exception
org.h2.jdbc.JdbcSQLDataException: Valor demasiado largo para la columna "USUARIO VARBINARY(255)": "X'aced000573720025636f6d2e73616c657369616e6f732e64616d2e44616d4b6565702e6d6f64656c2e557365729b212634ebb154ae0200095a001563726564... (1029)"
Value too long for column "USUARIO VARBINARY(255)": "X'aced000573720025636f6d2e73616c657369616e6f732e64616d2e44616d4b6565702e6d6f64656c2e557365729b212634ebb154ae0200095a001563726564... (1029)"; SQL statement:
insert into nota (contenido, fecha_creacion, fecha_modi, titulo, usuario, id) values (?, ?, ?, ?, ?, ?) [22001-200]
2020-05-15 19:01:23 jdbc[35]: null
org.h2.message.DbException: La conexi贸n no fue cerrada por la aplicaci贸n y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.get(DbException.java:205)
	at org.h2.message.DbException.get(DbException.java:181)
	at org.h2.message.DbException.get(DbException.java:170)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:245)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:186)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:152)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:725)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:711)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: La conexi贸n no fue cerrada por la aplicaci贸n y esta siendo limpiada (garbage collected)
The connection was not closed by the application and is garbage collected [90018-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	... 18 more
